### ISSUE TITLE
Signaturen

### ISSUE THREAD

**Issue by sebastianriese** [fsfw-dresden/protokolle#1]
Ich glaube es ist auf dauherhaft handhabbarer die signierte Tags zu verwenden, statt die Signaturen für jedes einzelnes Protokoll anzulegen. Das geht einfach per

```
git tag -s <tagname>
```

Ich würde als tagname einfach das datum des protokolls nehmen und `-vN` anhängen, wenn es nachträgliche Formatierung gibt.

Die Integrität garantiert git ja im Prinzip schon.

Dann muss man auch nur eine Signatur überprüfen, um sicherzustellen, dass alle Protokolle gültig sind
(`git tag -v <tagname>`).

**Comment by horazont** [comment]
Ein anderer Vorteil ist, dass mehrere Leute den gleichen Tag signieren können, ohne dass sehr viele Files im Repository rumliegen.

+1 von mir.

**Comment by exot** [comment]
Ich habe das jetzt mal so angefangen.  Zusätzlich habe ich auch meine commits jetzt signiert.  Die detached signatures habe ich gelöscht.

**Comment by sebastianriese** [comment]
Da das jetzt umgesetzt ist, kann der Issue geschlossen werden.
