### ISSUE TITLE
make update-all funktioniert nicht wie erwartet

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/protokolle#3]
Datei: liste-der-protokolle wurde aktualisiert. Aber `make update-all`hat nur die fehlenden von 2016 runtergeladen.

Weil ich mir eine Einarbeitung in die Makefile-Syntax sparen wollte, wäre es nett, wenn sich jemand mit entsprechender Kompetenz das mal ansehen könnte.

**Comment by sebastianriese** [comment]
Man muss `liste-der-protokolle` updaten. Das geht noch nicht automatisch. Aber das tool `dates.py` hilft dabei (man muss den quelltext anpassen und dann sollte `python3 dates.py >> liste-der-protokolle` machen was man will, eventuell muss man noch fehlende protokolle manuell herauseditieren – Weihnachten und so).

**Comment by cknoll** [comment]
Ah. Problem gelöst.
`liste-der-protokolle` hatte ich selber schon aktualisiert, aber schlecht. An Stelle von `python3 dates.py >> liste-der-protokolle` hatte ich das Ergebnis aus der Konsole per Zwischenablage kopiert und dabei die Zeilenenden mit haufenweise Leerzeichen verschmutzt. Damit kam das Makefile offenbar nicht klar. Werde mal die README.md und dates.py mit Warnhinweisen versehen.
